# Create 3 servers for testing
Vagrant.configure(2) do |config|
  config.vm.define "cr1" do |cr1|
    cr1.vm.box = "ubuntu/xenial64"
    cr1.vm.hostname = "cr1"
    cr1.vm.network :private_network, ip: "192.168.33.100"
    cr2.vm.network :forwarded_port, guest:8080, host:8080
  end

  config.vm.define "cr2" do |cr2|
    cr2.vm.box = "ubuntu/xenial64"
    cr2.vm.hostname = "cr2"
    cr2.vm.network :private_network, ip: "192.168.33.200"
  end

  config.vm.define "cr3" do |cr3|
    cr3.vm.box = "ubuntu/xenial64"
    cr3.vm.hostname = "cr3"
    cr3.vm.network :private_network, ip: "192.168.33.300"
  end
end
